# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_provisioning_profile(
	  app_identifier: "com.tnzkm.Trinap",
	  filename: "trinap_distribution.mobileprovision",
	  output_path: "./fastlane/profiles/"
	)
    increment_build_number(xcodeproj: "Trinap.xcodeproj")
    build_app(
	  workspace: "Trinap.xcworkspace", 
	  scheme: "Trinap",
	  export_method: "app-store",
	  export_options: {
	    provisioningProfiles: {
		  "com.tnzkm.Trinap" => "trinap_distribution.mobileprovision"
		}
	  }
	)
    upload_to_testflight
	slack(
	  message: "New Version of Trinap uploaded successfully at App Store Connect",
	  slack_url: "https://hooks.slack.com/services/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"
	)
  end

  error do |lane, exception, options|
    slack(
	  message: "App Store Connect - Error detected: #{exception}",
      success: false,
	  slack_url: "https://hooks.slack.com/services/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"
	)
  end
end
