# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

BundleId = "com.tnzkm.Trinap"
AppName = "Trinap"

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight in local"
  lane :local do

	increment_build_number({
		build_number: latest_testflight_build_number + 1
	})

	update_code_signing_settings(
		use_automatic_signing: false
 	)
  
	match(type: "appstore")

    build_app(
	  workspace: "Trinap.xcworkspace", 
	  scheme: "Trinap",
	  export_method: "app-store",
	  export_options: {
	    provisioningProfiles: {
		  "com.tnzkm.Trinap" => "Development_com.tnzkm.Trinap.mobileprovision"
		}
	  }
	)

    upload_to_testflight

	slack(
	  message: "New Version of Trinap uploaded successfully at App Store Connect",
	  slack_url: ENV['SLACK_URL']
	)
  end

  desc "build app and upload to testflight in remote"
  lane :remote do

	#app_store_connect_api_key 사용해서 2중 인증 회피
	app_store_connect_api_key(
	  key_id: ENV['API_KEY_ID'],
	  issuer_id: ENV['API_ISSUER_ID'],
	  key_content: ENV['API_PRIVATE_KEY'],
	  duration: 500,
	  in_house: false
	)

	sync_code_signing(
		type: "appstore",
		app_identifier: BundleId,
		readonly: false
	  )

	#testflight에 등록된 최신 빌드버전을 가져와 +1을 해준다.
	increment_build_number({
	  build_number: latest_testflight_build_number + 1
	})

	buildApp "Release"

	upload_to_testflight

  end

  desc "Get certificates"
  lane :certificates do

	app_store_connect_api_key(
	  key_id: ENV['API_KEY_ID'],
	  issuer_id: ENV['API_ISSUER_ID'],
	  key_content: ENV['API_PRIVATE_KEY'],
	  duration: 500,
	  in_house: false
	)
	
	ENV['MATCH_GIT_PRIVATE_KEY'] = "https://github.com/chansooo/TrinapCert"
	sync_code_signing(
	  type: "appstore",
	  app_identifier: BundleId,
	  readonly: false
	)
  end
  
  error do |lane, exception, options|
    slack(
	  message: "App Store Connect - Error detected: #{exception}",
      success: false,
	  slack_url: ENV['SLACK_URL']
	)
  end

end

def buildApp(configuration)
	#auto signing 세팅 해제.
  update_code_signing_settings(
		use_automatic_signing: false,
		path: AppName + ".xcodeproj"
  )
  
  build_app(
	  workspace: AppName + ".xcworkspace", 
	  scheme: AppName, 
	  configuration: configuration,
	  export_method: "app-store",
	  codesigning_identity: "Apple Distribution: Seyoung Kim (GTB6BR222W)",
	  export_options: {
		method: "app-store",
		provisioningProfiles: { 
			BundleId => 'match AppStore com.tnzkm.Trinap'
		}
	  }
	  )
end